import { Inter } from "next/font/google";
import Header from "./Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          "min-h-screen bg-gradient-to-r from-black via-blue-900 to-blue-600"
        }
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
